-- PMC-006: athlete_notifications table
--
-- Stores athlete-facing notifications generated by the fitting pipeline:
--   'personalization_available' – fired once when eligibility threshold first crossed
--   'model_updated'             – fired after every successful refit
--   'more_data_needed'          – fired after a refit whose R² < 0.6
--
-- confidence_label ('High' | 'Medium' | 'Low') is a display convenience derived
-- from ci_width at write time. ci_width (raw tc_fitness CI width in days) is the
-- authoritative value — update the mapping thresholds in getConfidenceLabel()
-- without a schema change.
--
-- Run once via the Supabase SQL editor. Idempotent (uses IF NOT EXISTS).
--
-- Prerequisites: athlete_parameters.sql (creates the athletes table reference)

CREATE TABLE IF NOT EXISTS athlete_notifications (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    athlete_id       UUID        NOT NULL REFERENCES athletes(id),
    sport            TEXT        NOT NULL,

    -- Notification category
    type             TEXT        NOT NULL
                                 CHECK (type IN (
                                     'personalization_available',
                                     'model_updated',
                                     'more_data_needed'
                                 )),

    -- Human-readable message surfaced in the UI
    message          TEXT        NOT NULL,

    -- Model quality at time of notification (NULL for personalization_available)
    r_squared        FLOAT,

    -- Display label derived from ci_width at write time
    -- 'High' = ci_width ≤ 10 days, 'Medium' ≤ 20 days, 'Low' > 20 days
    confidence_label TEXT        CHECK (confidence_label IN ('High', 'Medium', 'Low')),

    -- Raw tc_fitness CI width (tc_fitness_high - tc_fitness_low) in days.
    -- Stored alongside the label so thresholds can be updated without a schema change.
    ci_width         FLOAT,

    is_read          BOOLEAN     NOT NULL DEFAULT false,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for per-athlete unread feed
CREATE INDEX IF NOT EXISTS idx_athlete_notifications_athlete_read
    ON athlete_notifications (athlete_id, is_read, created_at DESC);

-- Grant access (RLS disabled, matching other tables)
GRANT SELECT, INSERT, UPDATE, DELETE ON athlete_notifications TO anon, authenticated;

ALTER TABLE athlete_notifications DISABLE ROW LEVEL SECURITY;

NOTIFY pgrst, 'reload schema';
